# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/rockchip/mk808b/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/rockchip/mk808b/proprietary/etc/firmware/MTK_MT6622_E2_Patch.nb0:system/etc/firmware/MTK_MT6622_E2_Patch.nb0 \
    vendor/rockchip/mk808b/proprietary/etc/firmware/RT5370AP.dat:system/etc/firmware/RT5370AP.dat \
    vendor/rockchip/mk808b/proprietary/etc/firmware/RT5370STA.dat:system/etc/firmware/RT5370STA.dat \
    vendor/rockchip/mk808b/proprietary/etc/firmware/WIFI_RAM_CODE:system/etc/firmware/WIFI_RAM_CODE \
    vendor/rockchip/mk808b/proprietary/etc/firmware/athtcmd_ram.bin:system/etc/firmware/athtcmd_ram.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/athwlan.bin.z77:system/etc/firmware/athwlan.bin.z77 \
    vendor/rockchip/mk808b/proprietary/etc/firmware/bdata.SD31.bin:system/etc/firmware/bdata.SD31.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/data.patch.hw2_0.bin:system/etc/firmware/data.patch.hw2_0.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/device.bin:system/etc/firmware/device.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK901.bin:system/etc/firmware/fw_RK901.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK901a0.bin:system/etc/firmware/fw_RK901a0.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK901a0_apsta.bin:system/etc/firmware/fw_RK901a0_apsta.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK901a2.bin:system/etc/firmware/fw_RK901a2.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK901a2_apsta.bin:system/etc/firmware/fw_RK901a2_apsta.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK901a2_p2p.bin:system/etc/firmware/fw_RK901a2_p2p.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903.bin:system/etc/firmware/fw_RK903.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903_ag.bin:system/etc/firmware/fw_RK903_ag.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903_ag_apsta.bin:system/etc/firmware/fw_RK903_ag_apsta.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903_ag_p2p.bin:system/etc/firmware/fw_RK903_ag_p2p.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903_p2p.bin:system/etc/firmware/fw_RK903_p2p.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903b2.bin:system/etc/firmware/fw_RK903b2.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903b2_apsta.bin:system/etc/firmware/fw_RK903b2_apsta.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_RK903b2_p2p.bin:system/etc/firmware/fw_RK903b2_p2p.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_bcm4319.bin:system/etc/firmware/fw_bcm4319.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_bcm4329.bin:system/etc/firmware/fw_bcm4329.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_bcm4329_apsta.bin:system/etc/firmware/fw_bcm4329_apsta.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_bcm4329_wapi.bin:system/etc/firmware/fw_bcm4329_wapi.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_bcm4330.bin:system/etc/firmware/fw_bcm4330.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/fw_bcm4330_apsta.bin:system/etc/firmware/fw_bcm4330_apsta.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram.txt:system/etc/firmware/nvram.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_4330.txt:system/etc/firmware/nvram_4330.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_AP6181.txt:system/etc/firmware/nvram_AP6181.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_AP6210.txt:system/etc/firmware/nvram_AP6210.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_AP6330.txt:system/etc/firmware/nvram_AP6330.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_AP6476.txt:system/etc/firmware/nvram_AP6476.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_AP6493.txt:system/etc/firmware/nvram_AP6493.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_B23.txt:system/etc/firmware/nvram_B23.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_GB86302I.txt:system/etc/firmware/nvram_GB86302I.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_RK901.txt:system/etc/firmware/nvram_RK901.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_RK903.cal:system/etc/firmware/nvram_RK903.cal \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_RK903.txt:system/etc/firmware/nvram_RK903.txt \
    vendor/rockchip/mk808b/proprietary/etc/firmware/nvram_RK903_26M.cal:system/etc/firmware/nvram_RK903_26M.cal \
	vendor/rockchip/mk808b/proprietary/etc/firmware/otp.bin.z77:system/etc/firmware/otp.bin.z77 \
    vendor/rockchip/mk808b/proprietary/etc/firmware/sd8686.bin:system/etc/firmware/sd8686.bin \
    vendor/rockchip/mk808b/proprietary/etc/firmware/sd8686_helper.bin:system/etc/firmware/sd8686_helper.bin

PRODUCT_COPY_FILES += \
    vendor/rockchip/mk808b/proprietary/lib/drm/libfwdlockengine.so:system/lib/drm/libfwdlockengine.so

PRODUCT_COPY_FILES += \
    vendor/rockchip/mk808b/proprietary/lib/egl/egl.cfg:system/lib/egl/egl.cfg

PRODUCT_COPY_FILES += \
    vendor/rockchip/mk808b/proprietary/lib/hw/acoustics.default.so:system/lib/hw/acoustics.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/camera.goldfish.so:system/lib/hw/camera.goldfish.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/gps.goldfish.so:system/lib/hw/gps.goldfish.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/lights.goldfish.so:system/lib/hw/lights.goldfish.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/power.default.so:system/lib/hw/power.default.so \
    vendor/rockchip/mk808b/proprietary/lib/hw/sensors.goldfish.so:system/lib/hw/sensors.goldfish.so


PRODUCT_COPY_FILES += \
    vendor/rockchip/mk808b/proprietary/lib/modules/8188eu.ko:system/lib/modules/8188eu.ko \
    vendor/rockchip/mk808b/proprietary/lib/modules/8188eu.ko.3.0.8+:system/lib/modules/8188eu.ko.3.0.8+ \
    vendor/rockchip/mk808b/proprietary/lib/modules/8192cu.ko:system/lib/modules/8192cu.ko \
    vendor/rockchip/mk808b/proprietary/lib/modules/8192cu.ko.3.0.8+:system/lib/modules/8192cu.ko.3.0.8+ \
    vendor/rockchip/mk808b/proprietary/lib/modules/rk30_mirroring.ko.3.0.36+:system/lib/modules/rk30_mirroring.ko.3.0.36+ \
    vendor/rockchip/mk808b/proprietary/lib/modules/rk30_mirroring.ko.3.0.8+:system/lib/modules/rk30_mirroring.ko.3.0.8+ \
    vendor/rockchip/mk808b/proprietary/lib/modules/rt5370ap.ko:system/lib/modules/rt5370ap.ko \
    vendor/rockchip/mk808b/proprietary/lib/modules/rt5370ap.ko.3.0.8+:system/lib/modules/rt5370ap.ko.3.0.8+ \
    vendor/rockchip/mk808b/proprietary/lib/modules/rt5370sta.ko:system/lib/modules/rt5370sta.ko \
    vendor/rockchip/mk808b/proprietary/lib/modules/rt5370sta.ko.3.0.8+:system/lib/modules/rt5370sta.ko.3.0.8+ \
    vendor/rockchip/mk808b/proprietary/lib/modules/vpu_service.ko:system/lib/modules/vpu_service.ko \
    vendor/rockchip/mk808b/proprietary/lib/modules/vpu_service.ko.3.0.36+:system/lib/modules/vpu_service.ko.3.0.36+

PRODUCT_COPY_FILES += \
    vendor/rockchip/mk808b/proprietary/lib/ssl/engines/libkeystore.so:system/lib/ssl/engines/libkeystore.so \
    vendor/rockchip/mk808b/proprietary/lib/webkit_ver:system/lib/webkit_ver

#PRODUCT_COPY_FILES += \
#	vendor/rockchip/mk808b/proprietary/lib/acoustics.default.so:system/lib/acoustics.default.so \
#    vendor/rockchip/mk808b/proprietary/lib/alsa.default.so:system/lib/alsa.default.so \
#    vendor/rockchip/mk808b/proprietary/lib/audio.primary.rk30board.so:system/lib/audio.primary.rk30board.so \
#    vendor/rockchip/mk808b/proprietary/lib/audio_policy.rk30board.so:system/lib/audio_policy.rk30board.so \
#    vendor/rockchip/mk808b/proprietary/lib/crtbegin_so.o:system/lib/crtbegin_so.o \
#    vendor/rockchip/mk808b/proprietary/lib/crtend_so.o:system/lib/crtend_so.o \
#    vendor/rockchip/mk808b/proprietary/lib/gralloc.rk30board.so:system/lib/gralloc.rk30board.so \
#    vendor/rockchip/mk808b/proprietary/lib/hwcomposer.rk30board.so:system/lib/hwcomposer.rk30board.so \
#    vendor/rockchip/mk808b/proprietary/lib/invoke_mock_media_player.so:system/lib/invoke_mock_media_player.so \
#    vendor/rockchip/mk808b/proprietary/lib/libEGL.so:system/lib/libEGL.so \
#    vendor/rockchip/mk808b/proprietary/lib/libETC1.so:system/lib/libETC1.so \
#    vendor/rockchip/mk808b/proprietary/lib/libFFTEm.so:system/lib/libFFTEm.so \
#    vendor/rockchip/mk808b/proprietary/lib/libGLES_trace.so:system/lib/libGLES_trace.so \
#    vendor/rockchip/mk808b/proprietary/lib/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
#    vendor/rockchip/mk808b/proprietary/lib/libGLESv2.so:system/lib/libGLESv2.so \
#    vendor/rockchip/mk808b/proprietary/lib/libMSPdf.861.so:system/lib/libMSPdf.861.so \
#    vendor/rockchip/mk808b/proprietary/lib/libOpenMAXAL.so:system/lib/libOpenMAXAL.so \
#    vendor/rockchip/mk808b/proprietary/lib/libOpenSLES.so:system/lib/libOpenSLES.so \
#    vendor/rockchip/mk808b/proprietary/lib/libRS.so:system/lib/libRS.so \
#    vendor/rockchip/mk808b/proprietary/lib/libRSDriver.so:system/lib/libRSDriver.so \
#    vendor/rockchip/mk808b/proprietary/lib/libSR_AudioIn.so:system/lib/libSR_AudioIn.so \
#    vendor/rockchip/mk808b/proprietary/lib/libWnnEngDic.so:system/lib/libWnnEngDic.so \
#    vendor/rockchip/mk808b/proprietary/lib/libWnnJpnDic.so:system/lib/libWnnJpnDic.so \
#    vendor/rockchip/mk808b/proprietary/lib/libandroid.so:system/lib/libandroid.so \
#    vendor/rockchip/mk808b/proprietary/lib/libandroid_runtime.so:system/lib/libandroid_runtime.so \
#    vendor/rockchip/mk808b/proprietary/lib/libandroid_servers.so:system/lib/libandroid_servers.so \
#    vendor/rockchip/mk808b/proprietary/lib/libandroidfw.so:system/lib/libandroidfw.so \
#    vendor/rockchip/mk808b/proprietary/lib/libapedec.so:system/lib/libapedec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libasan_preload.so:system/lib/libasan_preload.so \
#    vendor/rockchip/mk808b/proprietary/lib/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
#    vendor/rockchip/mk808b/proprietary/lib/libaudioutils.so:system/lib/libaudioutils.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbcc.sha1.so:system/lib/libbcc.sha1.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbcc.so:system/lib/libbcc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbcinfo.so:system/lib/libbcinfo.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbinder.so:system/lib/libbinder.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbluedroid.so:system/lib/libbluedroid.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbluetooth_jni.so:system/lib/libbluetooth_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbt-hci.so:system/lib/libbt-hci.so \
#    vendor/rockchip/mk808b/proprietary/lib/libbt-utils.so:system/lib/libbt-utils.so \
#    vendor/rockchip/mk808b/proprietary/lib/libc.so:system/lib/libc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libc_malloc_debug_leak.so:system/lib/libc_malloc_debug_leak.so \
#    vendor/rockchip/mk808b/proprietary/lib/libc_malloc_debug_qemu.so:system/lib/libc_malloc_debug_qemu.so \
#    vendor/rockchip/mk808b/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
#    vendor/rockchip/mk808b/proprietary/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
#    vendor/rockchip/mk808b/proprietary/lib/libcameraservice.so:system/lib/libcameraservice.so \
#    vendor/rockchip/mk808b/proprietary/lib/libchromeview.so:system/lib/libchromeview.so \
#    vendor/rockchip/mk808b/proprietary/lib/libchromium_net.so:system/lib/libchromium_net.so \
#    vendor/rockchip/mk808b/proprietary/lib/libclcore.bc:system/lib/libclcore.bc \
#    vendor/rockchip/mk808b/proprietary/lib/libclcore_neon.bc:system/lib/libclcore_neon.bc \
#    vendor/rockchip/mk808b/proprietary/lib/libcommon_time_client.so:system/lib/libcommon_time_client.so \
#    vendor/rockchip/mk808b/proprietary/lib/libcorkscrew.so:system/lib/libcorkscrew.so \
#    vendor/rockchip/mk808b/proprietary/lib/libcrypto.so:system/lib/libcrypto.so \
#    vendor/rockchip/mk808b/proprietary/lib/libctest.so:system/lib/libctest.so \
#    vendor/rockchip/mk808b/proprietary/lib/libcutils.so:system/lib/libcutils.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdbus.so:system/lib/libdbus.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdefcontainer_jni.so:system/lib/libdefcontainer_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdiskconfig.so:system/lib/libdiskconfig.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdl.so:system/lib/libdl.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdrm1.so:system/lib/libdrm1.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdrm1_jni.so:system/lib/libdrm1_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdrmframework.so:system/lib/libdrmframework.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdrmframework_jni.so:system/lib/libdrmframework_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libdvm.so:system/lib/libdvm.so \
#    vendor/rockchip/mk808b/proprietary/lib/libeffects.so:system/lib/libeffects.so \
#    vendor/rockchip/mk808b/proprietary/lib/libemoji.so:system/lib/libemoji.so \
#    vendor/rockchip/mk808b/proprietary/lib/libexif.so:system/lib/libexif.so \
#    vendor/rockchip/mk808b/proprietary/lib/libexif_jni.so:system/lib/libexif_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libexpat.so:system/lib/libexpat.so \
#    vendor/rockchip/mk808b/proprietary/lib/libext4_utils.so:system/lib/libext4_utils.so \
#    vendor/rockchip/mk808b/proprietary/lib/libffmpeg.so:system/lib/libffmpeg.so \
#    vendor/rockchip/mk808b/proprietary/lib/libfilterfw.so:system/lib/libfilterfw.so \
#    vendor/rockchip/mk808b/proprietary/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so \
#    vendor/rockchip/mk808b/proprietary/lib/libfilterpack_imageproc.so:system/lib/libfilterpack_imageproc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libfrsdk.so:system/lib/libfrsdk.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgabi++.so:system/lib/libgabi++.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgccdemangle.so:system/lib/libgccdemangle.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgcomm_jni.so:system/lib/libgcomm_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgoggles_clientvision.so:system/lib/libgoggles_clientvision.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgtalk_jni.so:system/lib/libgtalk_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgtalk_stabilize.so:system/lib/libgtalk_stabilize.so \
#    vendor/rockchip/mk808b/proprietary/lib/libgui.so:system/lib/libgui.so \
#    vendor/rockchip/mk808b/proprietary/lib/libhardware.so:system/lib/libhardware.so \
#    vendor/rockchip/mk808b/proprietary/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
#    vendor/rockchip/mk808b/proprietary/lib/libharfbuzz.so:system/lib/libharfbuzz.so \
#    vendor/rockchip/mk808b/proprietary/lib/libhtml5_check.so:system/lib/libhtml5_check.so \
#    vendor/rockchip/mk808b/proprietary/lib/libhwui.so:system/lib/libhwui.so \
#    vendor/rockchip/mk808b/proprietary/lib/libicui18n.so:system/lib/libicui18n.so \
#    vendor/rockchip/mk808b/proprietary/lib/libicuuc.so:system/lib/libicuuc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libinput.so:system/lib/libinput.so \
#    vendor/rockchip/mk808b/proprietary/lib/libiprouteutil.so:system/lib/libiprouteutil.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjavacore.so:system/lib/libjavacore.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjesancache.so:system/lib/libjesancache.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjni_eglfence.so:system/lib/libjni_eglfence.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjni_filtershow_filters.so:system/lib/libjni_filtershow_filters.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjni_latinime.so:system/lib/libjni_latinime.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjni_mosaic.so:system/lib/libjni_mosaic.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjni_pinyinime.so:system/lib/libjni_pinyinime.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjnigraphics.so:system/lib/libjnigraphics.so \
#    vendor/rockchip/mk808b/proprietary/lib/libjpeg.so:system/lib/libjpeg.so \
#    vendor/rockchip/mk808b/proprietary/lib/libkeystore_client.so:system/lib/libkeystore_client.so \
#    vendor/rockchip/mk808b/proprietary/lib/liblog.so:system/lib/liblog.so \
#    vendor/rockchip/mk808b/proprietary/lib/libm.so:system/lib/libm.so \
#    vendor/rockchip/mk808b/proprietary/lib/libmdnssd.so:system/lib/libmdnssd.so \
#    vendor/rockchip/mk808b/proprietary/lib/libmedia.so:system/lib/libmedia.so \
#    vendor/rockchip/mk808b/proprietary/lib/libmedia_jni.so:system/lib/libmedia_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libmedia_native.so:system/lib/libmedia_native.so \
#    vendor/rockchip/mk808b/proprietary/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
#    vendor/rockchip/mk808b/proprietary/lib/libmtp.so:system/lib/libmtp.so \
#    vendor/rockchip/mk808b/proprietary/lib/libnativehelper.so:system/lib/libnativehelper.so \
#    vendor/rockchip/mk808b/proprietary/lib/libnbaio.so:system/lib/libnbaio.so \
#    vendor/rockchip/mk808b/proprietary/lib/libnetlink.so:system/lib/libnetlink.so \
#    vendor/rockchip/mk808b/proprietary/lib/libnetutils.so:system/lib/libnetutils.so \
#    vendor/rockchip/mk808b/proprietary/lib/libnfc_ndef.so:system/lib/libnfc_ndef.so \
#    vendor/rockchip/mk808b/proprietary/lib/libntfs-3g.so:system/lib/libntfs-3g.so \
#    vendor/rockchip/mk808b/proprietary/lib/libpagemap.so:system/lib/libpagemap.so \
#    vendor/rockchip/mk808b/proprietary/lib/libpatts_engine_jni_api.so:system/lib/libpatts_engine_jni_api.so \
#    vendor/rockchip/mk808b/proprietary/lib/libpcmhost_skype.so:system/lib/libpcmhost_skype.so \
#    vendor/rockchip/mk808b/proprietary/lib/libperformance_runtime.so:system/lib/libperformance_runtime.so \
#    vendor/rockchip/mk808b/proprietary/lib/libpixelflinger.so:system/lib/libpixelflinger.so \
#    vendor/rockchip/mk808b/proprietary/lib/libportable.so:system/lib/libportable.so \
#    vendor/rockchip/mk808b/proprietary/lib/libpower.so:system/lib/libpower.so \
#    vendor/rockchip/mk808b/proprietary/lib/libpowermanager.so:system/lib/libpowermanager.so \
#    vendor/rockchip/mk808b/proprietary/lib/libppbox-armandroid-r4-gcc44-mt-1.0.0.so:system/lib/libppbox-armandroid-r4-gcc44-mt-1.0.0.so \
#    vendor/rockchip/mk808b/proprietary/lib/libppbox_jni-armandroid-r4-gcc44-mt-1.0.0.so:system/lib/libppbox_jni-armandroid-r4-gcc44-mt-1.0.0.so \
#    vendor/rockchip/mk808b/proprietary/lib/libpplive_dmc_jni.so:system/lib/libpplive_dmc_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
#    vendor/rockchip/mk808b/proprietary/lib/libril.so:system/lib/libril.so \
#    vendor/rockchip/mk808b/proprietary/lib/librk_on2.so:system/lib/librk_on2.so \
#    vendor/rockchip/mk808b/proprietary/lib/librkffplayer.so:system/lib/librkffplayer.so \
#    vendor/rockchip/mk808b/proprietary/lib/librkwmapro.so:system/lib/librkwmapro.so \
#    vendor/rockchip/mk808b/proprietary/lib/librockchip_update_jni.so:system/lib/librockchip_update_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/librs_jni.so:system/lib/librs_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/librtp_jni.so:system/lib/librtp_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libselinux.so:system/lib/libselinux.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsensorservice.so:system/lib/libsensorservice.so \
#    vendor/rockchip/mk808b/proprietary/lib/libskia.so:system/lib/libskia.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsonivox.so:system/lib/libsonivox.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsoundpool.so:system/lib/libsoundpool.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsparse.so:system/lib/libsparse.so \
#    vendor/rockchip/mk808b/proprietary/lib/libspeexresampler.so:system/lib/libspeexresampler.so \
#    vendor/rockchip/mk808b/proprietary/lib/libspeexwrapper.so:system/lib/libspeexwrapper.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsqlite.so:system/lib/libsqlite.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsqlite_jni.so:system/lib/libsqlite_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsrec_jni.so:system/lib/libsrec_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libssl.so:system/lib/libssl.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright.so:system/lib/libstagefright.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_amrnb_common.so:system/lib/libstagefright_amrnb_common.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_avc_common.so:system/lib/libstagefright_avc_common.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_chromium_http.so:system/lib/libstagefright_chromium_http.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_enc_common.so:system/lib/libstagefright_enc_common.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_aacdec.so:system/lib/libstagefright_soft_aacdec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_aacenc.so:system/lib/libstagefright_soft_aacenc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_amrdec.so:system/lib/libstagefright_soft_amrdec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_amrnbenc.so:system/lib/libstagefright_soft_amrnbenc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_amrwbenc.so:system/lib/libstagefright_soft_amrwbenc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_flacenc.so:system/lib/libstagefright_soft_flacenc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_g711dec.so:system/lib/libstagefright_soft_g711dec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_h264dec.so:system/lib/libstagefright_soft_h264dec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_h264enc.so:system/lib/libstagefright_soft_h264enc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_mp3dec.so:system/lib/libstagefright_soft_mp3dec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_mpeg4dec.so:system/lib/libstagefright_soft_mpeg4dec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_mpeg4enc.so:system/lib/libstagefright_soft_mpeg4enc.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_rawdec.so:system/lib/libstagefright_soft_rawdec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_vorbisdec.so:system/lib/libstagefright_soft_vorbisdec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_soft_vpxdec.so:system/lib/libstagefright_soft_vpxdec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_wfd.so:system/lib/libstagefright_wfd.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstagefright_yuv.so:system/lib/libstagefright_yuv.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstdc++.so:system/lib/libstdc++.so \
#    vendor/rockchip/mk808b/proprietary/lib/libstlport.so:system/lib/libstlport.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsurfaceflinger_ddmconnection.so:system/lib/libsurfaceflinger_ddmconnection.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsuspend.so:system/lib/libsuspend.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsync.so:system/lib/libsync.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsystem_server.so:system/lib/libsystem_server.so \
#    vendor/rockchip/mk808b/proprietary/lib/libsysutils.so:system/lib/libsysutils.so \
#    vendor/rockchip/mk808b/proprietary/lib/libthread_db.so:system/lib/libthread_db.so \
#    vendor/rockchip/mk808b/proprietary/lib/libttscompat.so:system/lib/libttscompat.so \
#    vendor/rockchip/mk808b/proprietary/lib/libttspico.so:system/lib/libttspico.so \
#    vendor/rockchip/mk808b/proprietary/lib/libui.so:system/lib/libui.so \
#    vendor/rockchip/mk808b/proprietary/lib/libusbhost.so:system/lib/libusbhost.so \
#    vendor/rockchip/mk808b/proprietary/lib/libutils.so:system/lib/libutils.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvariablespeed.so:system/lib/libvariablespeed.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvideoeditor_core.so:system/lib/libvideoeditor_core.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvideoeditor_jni.so:system/lib/libvideoeditor_jni.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvideoeditor_osal.so:system/lib/libvideoeditor_osal.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvideoeditor_videofilters.so:system/lib/libvideoeditor_videofilters.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvideoeditorplayer.so:system/lib/libvideoeditorplayer.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvideohost_skype.so:system/lib/libvideohost_skype.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvinit.so:system/lib/libvinit.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvorbisencoder.so:system/lib/libvorbisencoder.so \
#    vendor/rockchip/mk808b/proprietary/lib/libvorbisidec.so:system/lib/libvorbisidec.so \
#    vendor/rockchip/mk808b/proprietary/lib/libwebcore.so:system/lib/libwebcore.so \
#    vendor/rockchip/mk808b/proprietary/lib/libwebrtc_audio_preprocessing.so:system/lib/libwebrtc_audio_preprocessing.so \
#    vendor/rockchip/mk808b/proprietary/lib/libwilhelm.so:system/lib/libwilhelm.so \
#    vendor/rockchip/mk808b/proprietary/lib/libwimo.so:system/lib/libwimo.so \
#    vendor/rockchip/mk808b/proprietary/lib/libwnndict.so:system/lib/libwnndict.so \
#    vendor/rockchip/mk808b/proprietary/lib/libwpa_client.so:system/lib/libwpa_client.so \
#    vendor/rockchip/mk808b/proprietary/lib/libz.so:system/lib/libz.so
