#! /usr/bin/env sh

sed -i 's|proprietary/etc/firmware/athtcmd_ram.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/athwlan.bin.z77|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/bdata.SD31.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/data.patch.hw2_0.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/device.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_bcm4319.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_bcm4329_apsta.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_bcm4329.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_bcm4329_wapi.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_bcm4330_apsta.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_bcm4330.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK901a0_apsta.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK901a0.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK901a2_apsta.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK901a2.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK901a2_p2p.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK901.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK903b2_apsta.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK903b2.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK903b2_p2p.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK903.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/fw_RK903_p2p.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/nvram_4330.txt|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/nvram_B23.txt|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/nvram_RK901.txt|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/nvram_RK903_26M.cal|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/nvram_RK903.cal|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/nvram_RK903.txt|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/nvram.txt|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/otp.bin.z77|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/sd8686.bin|removed|g' mk808b-vendor.mk
sed -i 's|proprietary/etc/firmware/sd8686_helper.bin|removed|g' mk808b-vendor.mk
